spring:
  # 国际化配置
  messages:
    basename: i18n/message
  # 选择环境
  profiles:
    active: debug

sm2-key-pair:
  private-key-hex:
  public-key-hex:

---
debug: false
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kingyan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

http-header:
  # 允许浏览器跨域访问
  # 部署时若用nginx代理，前后端同源，则本地调试时，更推荐用以下命令启动chrome进行调试
  # "C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-site-isolation-trials --disable-web-security --user-data-dir="D:\chrome-temp"

  # 允许一个固定的域访问
  access-control-allow-origin: http://localhost:8085
  # 允许所有域访问，上面未设置才生效
  allow-CORS: true

config:
    activate:
      on-profile: debug
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: prd